### ISSUE TITLE
EasyRec 训练慢怎么办，怎么设置参数？

### ISSUE THREAD

**Issue by poson** [AlibabaPAI/EasyRec#50]
要么提高计算资源，例如：
（1）增加ps 的数量，从1增加到2，再增加到4，不要一次增加太多。
（2）worker 的cpu设置为1600，处理数据的并行程度增加。
（3）增加worker的数量。

要么缩小网络：把item 和room 的网络合并；把final dnn 缩小。

sync_replicas: false。同步训练修改为异步训练。

**Comment by fooSynaptic** [comment]
理论上可以增加一些算子优化工具来让cpu训练更快一些

btw easy_rec没有分布式train的setting吧
